// Resolve a schema (its groups + loose vars) into a grouped .env document, and
// write it to a project's linked path.

import { dirname, isAbsolute, join } from "./pathutil.ts";
import type { Schema, Variable } from "./types.ts";
import type { Store } from "./store.ts";
import { serializeValue } from "./dotenv.ts";

export interface GenSection {
  title: string; // group name, or "ungrouped" for loose vars
  variables: Variable[];
}

/**
 * Resolve which variables a schema includes, as ordered sections: one per
 * included group (in schema.groupIds order), then an "ungrouped" section for
 * loose variableIds not already provided by an included group.
 */
export function resolveSchema(store: Store, schema: Schema): GenSection[] {
  const sections: GenSection[] = [];
  const seen = new Set<string>();

  for (const gid of schema.groupIds) {
    let groupExists = true;
    try { store.groupById(gid); } catch { groupExists = false; }
    if (!groupExists) continue;
    const group = store.groupById(gid);
    const vars = store.variablesInGroup(schema.spaceId, group.id);
    for (const v of vars) seen.add(v.id);
    sections.push({ title: group.name, variables: vars });
  }

  const loose: Variable[] = [];
  for (const vid of schema.variableIds) {
    if (seen.has(vid)) continue;
    let v: Variable | undefined;
    try { v = store.variableById(vid); } catch { v = undefined; }
    if (v) {
      loose.push(v);
      seen.add(v.id);
    }
  }
  if (loose.length) sections.push({ title: "ungrouped", variables: loose });

  return sections;
}

export interface RenderResult {
  schemaName: string;
  content: string;
  sections: { title: string; keys: string[] }[];
  count: number;
}

/**
 * Render a schema into .env text. With `example: true` it produces a
 * committable `.env.example`: secret values are blanked, non-secret values are
 * kept as defaults, notes and section headers are preserved.
 */
export function renderEnv(store: Store, schema: Schema, opts: { example?: boolean } = {}): RenderResult {
  const sections = resolveSchema(store, schema);
  const lines: string[] = [];
  if (opts.example) {
    lines.push(`# .env.example for schema: ${schema.name}`);
    lines.push("# Generated by defenv. Keys only - fill in the values.");
  } else {
    lines.push(`# Generated by defenv on ${new Date().toISOString()}`);
    lines.push(`# schema: ${schema.name}`);
    lines.push("# Do not edit by hand - manage in defenv and regenerate.");
  }
  lines.push("");

  let count = 0;
  const summary: { title: string; keys: string[] }[] = [];
  for (const section of sections) {
    if (!section.variables.length) continue;
    lines.push(`# ---- ${section.title} ----`);
    const keys: string[] = [];
    for (const v of section.variables) {
      if (v.description) lines.push(`# ${v.description}`);
      lines.push(opts.example ? `${v.key}=` : `${v.key}=${serializeValue(v.value, v.quoted)}`);
      keys.push(v.key);
      count++;
    }
    lines.push("");
    summary.push({ title: section.title, keys });
  }

  return { schemaName: schema.name, content: lines.join("\n"), sections: summary, count };
}

/** Resolve a project/clone path to the .env file to write (dir -> dir/.env). */
export function envFileFor(path: string): string {
  const abs = isAbsolute(path) ? path : join(Deno.cwd(), path);
  const base = abs.split(/[/\\]/).pop() ?? "";
  return base.includes(".") || base === ".env" ? abs : join(abs, ".env");
}

/** The sibling .env.example path for a project path. */
export function exampleFileFor(path: string): string {
  return join(dirname(envFileFor(path)), ".env.example");
}

export interface ProjectGenResult {
  path: string;
  content: string;
  count: number;
}

/** Generate a project's linked schema into a .env written at its path. */
export async function generateProject(store: Store, projectId: string): Promise<ProjectGenResult> {
  const project = store.projectById(projectId);
  const schema = store.schemaById(project.schemaId);
  const res = renderEnv(store, schema);
  const file = envFileFor(project.path);
  await Deno.writeTextFile(file, res.content);
  return { path: file, content: res.content, count: res.count };
}

/** Generate a project's .env.example (secrets blanked) next to its .env. */
export async function generateProjectExample(store: Store, projectId: string): Promise<ProjectGenResult> {
  const project = store.projectById(projectId);
  const schema = store.schemaById(project.schemaId);
  const res = renderEnv(store, schema, { example: true });
  const file = exampleFileFor(project.path);
  await Deno.writeTextFile(file, res.content);
  return { path: file, content: res.content, count: res.count };
}
