// Embed static/ (index.html, app.js) into src/server/assets.ts so the binary is
// fully self-contained. Run after editing the UI:  node scripts/embed.cjs
const fs = require("fs"), path = require("path");
const root = path.join(__dirname, "..");
const files = { "/": "static/index.html", "/app.js": "static/app.js" };
const out = {};
for (const [route, rel] of Object.entries(files)) {
  out[route] = fs.readFileSync(path.join(root, rel), "utf8");
}
const body = "// AUTO-GENERATED by scripts/embed.cjs from static/. Do not edit by hand.\n" +
  "export const ASSETS: Record<string, string> = " + JSON.stringify(out) + ";\n";
fs.writeFileSync(path.join(root, "src", "server", "assets.ts"), body);
console.log("embedded", Object.keys(out).length, "asset(s) into src/server/assets.ts");
